import os

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.pdfgen.canvas import Canvas
from reportlab.platypus import (
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from app.models.meeting import Meeting


class PDFService:
    REPORT_DIR = "reports/generated"

    @staticmethod
    def _add_footer(canvas: Canvas, doc):
        canvas.saveState()

        canvas.setFont("Helvetica", 9)

        canvas.setFillColor(colors.grey)

        canvas.drawString(
            40,
            20,
            "Generated by AI Meeting Intelligence Platform",
        )

        canvas.drawRightString(
            550,
            20,
            f"Page {doc.page}",
        )

        canvas.restoreState()

    @staticmethod
    def generate_report(meeting: Meeting) -> str:
        os.makedirs(PDFService.REPORT_DIR, exist_ok=True)

        filename = f"meeting_{meeting.id}_report.pdf"
        filepath = os.path.join(PDFService.REPORT_DIR, filename)

        doc = SimpleDocTemplate(
            filepath,
            rightMargin=40,
            leftMargin=40,
            topMargin=40,
            bottomMargin=40,
        )

        styles = getSampleStyleSheet()

        title_style = styles["Title"]
        title_style.alignment = TA_CENTER
        title_style.textColor = colors.HexColor("#0F4C81")

        heading_style = styles["Heading2"]
        heading_style.textColor = colors.HexColor("#0F4C81")

        body_style = styles["BodyText"]

        story = []

        story.append(
            Paragraph(
                "<b>AI Meeting Intelligence Report</b>",
                title_style,
            )
        )

        story.append(Spacer(1, 0.30 * inch))

        meeting_data = [
           ["Meeting ID", str(meeting.id)],
           ["Meeting Title", meeting.title or "-"],
           ["Description", meeting.description or "-"],
           ["Created At", meeting.created_at.strftime("%d %b %Y %I:%M %p") if meeting.created_at else "-"],
           ["Sentiment", meeting.sentiment or "-"],
        ]

        table = Table(
            meeting_data,
            colWidths=[150, 330],
        )

        table.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#0F4C81")),
                    ("TEXTCOLOR", (0, 0), (0, -1), colors.white),
                    ("BACKGROUND", (1, 0), (1, -1), colors.beige),
                    ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
                    ("TOPPADDING", (0, 0), (-1, -1), 8),
                    ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                ]
            )
        )

        story.append(table)

        story.append(Spacer(1, 0.30 * inch))


        story.append(
            Paragraph("<b>AI Summary</b>", heading_style)
        )

        story.append(
            Paragraph(
                meeting.summary or "No summary available.",
                body_style,
            )
        )

        story.append(Spacer(1, 0.25 * inch))

       

        story.append(
            Paragraph("<b>Action Items</b>", heading_style)
        )

        if meeting.action_items:
            for item in meeting.action_items:
                story.append(
                    Paragraph(f"• {item}", body_style)
                )
        else:
            story.append(
                Paragraph("No action items.", body_style)
            )

        story.append(Spacer(1, 0.25 * inch))


        story.append(
            Paragraph("<b>Key Decisions</b>", heading_style)
        )

        if meeting.key_decisions:
            for item in meeting.key_decisions:
                story.append(
                    Paragraph(f"• {item}", body_style)
                )
        else:
            story.append(
                Paragraph("No key decisions.", body_style)
            )

        story.append(Spacer(1, 0.25 * inch))

        # ============================================================
        # Risks
        # ============================================================

        story.append(
            Paragraph("<b>Risks</b>", heading_style)
        )

        if meeting.risks:
            for item in meeting.risks:
                story.append(
                    Paragraph(f"• {item}", body_style)
                )
        else:
            story.append(
                Paragraph("No risks identified.", body_style)
            )

        story.append(Spacer(1, 0.25 * inch))

        # ============================================================
        # Sentiment
        # ============================================================

        story.append(
            Paragraph("<b>Sentiment</b>", heading_style)
        )

        story.append(
            Paragraph(
                meeting.sentiment or "Unknown",
                body_style,
            )
        )

        story.append(Spacer(1, 0.25 * inch))

        # ============================================================
        # Transcript
        # ============================================================

        story.append(
            Paragraph("<b>Transcript</b>", heading_style)
        )

        story.append(
            Paragraph(
                meeting.transcript or "No transcript available.",
                body_style,
            )
        )

        doc.build(
            story,
            onFirstPage=PDFService._add_footer,
            onLaterPages=PDFService._add_footer,
        )

        return filepath