"""add audio path to meetings

Revision ID: 3be18d946f10
Revises: a88d1e55c089
Create Date: 2026-07-30 02:39:30.733174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3be18d946f10'
down_revision: Union[str, Sequence[str], None] = 'a88d1e55c089'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('meetings', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('meetings', sa.Column('audio_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetings', 'audio_path')
    op.drop_column('meetings', 'updated_at')
    op.drop_column('meetings', 'created_at')
    # ### end Alembic commands ###
