"""add ai summary fields to meetings

Revision ID: 3fd59a21286d
Revises: 300920f09254
Create Date: 2026-07-30 20:27:40.058875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fd59a21286d'
down_revision: Union[str, Sequence[str], None] = '300920f09254'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('meetings', sa.Column('action_items', sa.JSON(), nullable=True))
    op.add_column('meetings', sa.Column('key_decisions', sa.JSON(), nullable=True))
    op.add_column('meetings', sa.Column('risks', sa.JSON(), nullable=True))
    op.add_column('meetings', sa.Column('sentiment', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetings', 'sentiment')
    op.drop_column('meetings', 'risks')
    op.drop_column('meetings', 'key_decisions')
    op.drop_column('meetings', 'action_items')
    op.drop_column('meetings', 'summary')
    # ### end Alembic commands ###
