"""add meeting embedding

Revision ID: f11fffd57bba
Revises: 3fd59a21286d
Create Date: 2026-07-31 19:49:15.543389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'f11fffd57bba'
down_revision: Union[str, Sequence[str], None] = '3fd59a21286d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('embedding', Vector(1536), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetings', 'embedding')
    # ### end Alembic commands ###
